#!/bin/bash

clear

readyjs ./www/js/models -o theodorus.models.min.js
mv theodorus.models.min.js ./www/js

readyjs ./www/js/controllers -o theodorus.controllers.min.js
mv theodorus.controllers.min.js ./www/js

readyjs ./www/js/views -o theodorus.views.min.js
mv theodorus.views.min.js ./www/js

# Invoke the Forever module (to START our Node.js server).
forever \
start \
-al forever.log \
-ao logs/out.log \
-ae logs/err.log \
./server.js
